# Generated by Django 6.0.3 on 2026-03-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncoderReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the encoder reading was recorded')),
                ('encoder_count', models.IntegerField(help_text='Raw encoder pulse counter value')),
                ('belt_position_mm', models.FloatField(help_text='Calculated belt position in millimeters along the belt loop')),
                ('belt', models.ForeignKey(help_text='The conveyor belt this encoder reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='encoder_readings', to='configuration.belt')),
            ],
            options={
                'verbose_name': 'Encoder Reading',
                'verbose_name_plural': 'Encoder Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the sensor reading was recorded')),
                ('voltage_v', models.FloatField(help_text='Voltage measured from the sensor circuit in volts')),
                ('capacitance_pf', models.FloatField(blank=True, help_text='Calculated capacitance in picofarads using calibration polynomial', null=True)),
                ('encoder_reading', models.ForeignKey(help_text='The encoder reading associated with this sensor measurement', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='acquisition.encoderreading')),
                ('sensor', models.ForeignKey(help_text='The sensor this reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='configuration.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
