from django.db import models


class Belt(models.Model):
    """
    Represents a conveyor belt used in an industrial wear monitoring system.
    """
    name = models.CharField(
        max_length=100,
        help_text="Name or identifier of the conveyor belt"
    )
    length_m = models.FloatField(
        help_text="Total belt length in meters"
    )
    width_mm = models.FloatField(
        help_text="Width of the belt in millimeters"
    )
    speed_m_s = models.FloatField(
        help_text="Belt speed in meters per second"
    )
    encoder_pulses_per_revolution = models.IntegerField(
        help_text="Number of pulses generated by the encoder per full rotation"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the belt was registered"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Timestamp of the last update"
    )

    class Meta:
        verbose_name = "Belt"
        verbose_name_plural = "Belts"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.length_m}m x {self.width_mm}mm)"
