# Generated by Django 6.0.3 on 2026-03-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of the conveyor belt', max_length=100)),
                ('length_m', models.FloatField(help_text='Total belt length in meters')),
                ('width_mm', models.FloatField(help_text='Width of the belt in millimeters')),
                ('speed_m_s', models.FloatField(help_text='Belt speed in meters per second')),
                ('encoder_pulses_per_revolution', models.IntegerField(help_text='Number of pulses generated by the encoder per full rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the belt was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
            options={
                'verbose_name': 'Belt',
                'verbose_name_plural': 'Belts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of the calibration', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the calibration procedure', null=True)),
                ('fixed_capacitor_pf', models.FloatField(help_text='Fixed capacitor value in picofarads (pF) used in the circuit')),
                ('a4', models.FloatField(blank=True, help_text='Coefficient for V^4 term in polynomial', null=True)),
                ('a3', models.FloatField(blank=True, help_text='Coefficient for V^3 term in polynomial', null=True)),
                ('a2', models.FloatField(blank=True, help_text='Coefficient for V^2 term in polynomial', null=True)),
                ('a1', models.FloatField(blank=True, help_text='Coefficient for V term in polynomial', null=True)),
                ('a0', models.FloatField(blank=True, help_text='Constant term in polynomial', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the calibration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
            options={
                'verbose_name': 'Sensor Calibration',
                'verbose_name_plural': 'Sensor Calibrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_capacitor_pf', models.FloatField(help_text='Known capacitance value of the variable capacitor in picofarads (pF)')),
                ('measured_voltage_v', models.FloatField(help_text='Measured voltage output from the sensor in volts (V)')),
                ('calibration', models.ForeignKey(help_text='The calibration this point belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calibration_points', to='configuration.sensorcalibration')),
            ],
            options={
                'verbose_name': 'Calibration Point',
                'verbose_name_plural': 'Calibration Points',
                'ordering': ['variable_capacitor_pf'],
                'unique_together': {('calibration', 'variable_capacitor_pf')},
            },
        ),
    ]
