# Generated by Django 6.0.3 on 2026-03-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_number', models.IntegerField(help_text='Physical sensor index (1-16)')),
                ('enabled', models.BooleanField(default=False, help_text='Enable/disable sensor operation')),
                ('plate_size_mm', models.FloatField(help_text='Side length of the square capacitive plate in millimeters')),
                ('offset_longitudinal_mm', models.FloatField(help_text='Position offset along belt direction. Positive = belt movement direction, Negative = opposite direction')),
                ('offset_lateral_mm', models.FloatField(help_text='Distance from belt top edge to sensor plate start in millimeters')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the sensor was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('belt', models.ForeignKey(help_text='The conveyor belt this sensor is mounted on', on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='configuration.belt')),
                ('calibration', models.ForeignKey(blank=True, help_text='Calibration curve for voltage-to-capacitance conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='configuration.sensorcalibration')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['sensor_number'],
                'unique_together': {('belt', 'sensor_number')},
            },
        ),
    ]
