# Generated by Django 6.0.3 on 2026-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcalibration',
            name='max_capacitance_pf',
            field=models.FloatField(blank=True, help_text='Capacitance at 3.3V (maximum reference)', null=True),
        ),
        migrations.AddField(
            model_name='sensorcalibration',
            name='min_capacitance_pf',
            field=models.FloatField(blank=True, help_text='Capacitance at 0V (minimum reference)', null=True),
        ),
    ]
