# Generated by Django 6.0.3 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_sensorcalibration_max_capacitance_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcalibration',
            name='max_voltage_v',
            field=models.FloatField(default=3.3, help_text='Maximum voltage reference for normalization (default 3.3V)'),
        ),
        migrations.AlterField(
            model_name='sensorcalibration',
            name='max_capacitance_pf',
            field=models.FloatField(blank=True, help_text='Capacitance at max_voltage_v (maximum reference)', null=True),
        ),
    ]
