# Generated by Django 6.0.3 on 2026-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_sensorcalibration_max_voltage_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcalibration',
            name='min_voltage_v',
            field=models.FloatField(default=0.0, help_text='Minimum voltage reference for normalization (default 0V)'),
        ),
    ]
